config/routes.rb
Rails.application.routes.draw do
  root to: 'sessions#new'
  post 'login_user', to: 'sessions#login_user'
  delete 'logout_user', to: 'sessions#logout_user'
  post 'login_artist', to: 'sessions#login_artist'
  delete 'logout_artist', to: 'sessions#logout_artist'
  resource :embed, only: %i[update]
  resources :artworks, only: %i[index] do
    member do
      put :move
    end
  end
  draw :admin
  draw :artist_module
  draw :api
  draw :sidekiq
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/artist.rb
# == Schema Information
#
# Table name: artists
#
#  id              :bigint           not null, primary key
#  about           :text
#  email           :string
#  instagram       :string
#  name            :string
#  password_digest :string
#  slug            :string
#  statement       :text
#  status          :integer
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
# Indexes
#
#  index_artists_on_slug  (slug) UNIQUE
#
class Artist < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged

  has_secure_password
  has_one_attached :avatar
  has_one :series
  has_many :posts
  has_many :social_media
  has_many :artworks

  accepts_nested_attributes_for :social_media, reject_if: :all_blank, allow_destroy: true

  validates :name, :email, :about, :statement, presence: true
  validates :status, presence: true

  enum status: %i[active inactive]

  def roshan?
    id.eql?(10)
  end
end

app/controllers/admin/artists_controller.rb
module Admin
  class ArtistsController < ApplicationController
    before_action :set_artist, except: %i[index new create]

    def index
      artists = ArtistPresenter.from_list(Artist.all.order(id: :asc))
      @artists = Kaminari.paginate_array(artists)
                         .page(params[:page])
                         .per(10)
    end

    def new
      @artist = Artist.new
    end

    def create
      @artist = Artist.new(artist_params.merge(password: temporary_password))
      if @artist.save
        redirect_to admin_artist_path(@artist), success: "#{@artist.name} successfully created."
      else
        flash[:danger] = artist_errors
        render :new
      end
    end

    def edit
      redirect_to admin_artists_path, warning: "Artist not found." unless @artist.present?
    end
    
    def update
      @artist.assign_attributes(artist_params)
      if @artist.save
        redirect_to admin_artist_path(@artist), success: "#{@artist.name} successfully updated."
      else
        flash[:danger] = artist_errors
        render :edit
      end
    end

    def show
      redirect_to admin_artists_path, warning: "Artist not found." unless @artist.present?
      @artist = ArtistPresenter.new(@artist)
    end

    def reset_password
      @artist.update(password: temporary_password)
      artists_mailer.send_reset_password_email(temporary_password: temporary_password)
                    .deliver_later
    end

    def send_welcome_email
      @artist.update(password: temporary_password)
      artists_mailer.send_welcome_email(temporary_password: temporary_password)
                    .deliver_later
    end

    private

    def set_artist
      @artist = Artist.includes(:artworks).friendly.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      redirect_to admin_artists_path, warning: "Artist not found."
    end

    def artist_params
      params.require(:artist).permit(
        :avatar,
        :name,
        :email,
        :instagram,
        :about,
        :statement,
        :status,
        social_media_attributes: [
          :id,
          :medium,
          :handle,
          :_destroy
        ]
      )
    end

    def temporary_password
      @temporary_password ||= SecureRandom.hex(10)
    end

    def artists_mailer
      ArtistsMailer.with(artist_id: @artist.id)
    end

    def artist_errors
      @artist.errors.full_messages.join(', ')
    end
  end
end

app/controllers/api/metaverse/artists_controller.rb
module Api
  module Metaverse
    class ArtistsController < Api::ApplicationController
      def show
        @artist = Artist.find_by(id: params[:id])
        return error("Artist not found", 404) unless @artist.present?
      end
    end
  end
end

app/controllers/api/v1/artists_controller.rb
module Api
  module V1
    class ArtistsController < Api::ApplicationController
      before_action :set_artist, only: %i[show]
      caches_action :index, expires_in: 1.hour

      def index
        @artists = Artist.active.order(name: :asc)
      end

      def show
        @posts = @artist.posts.with_rich_text_body_and_embeds.published.order(published_at: :asc)
      end

      private

      def set_artist
        @artist = Artist.find_by(id: params[:id])
        return error('Artist not found', 404) unless @artist
      end
    end
  end
end

app/views/artists/_form.html.erb
<%= form_with model: @artist, method: @artist.new_record? ? :post : :put do |form| %>
  <div class="row">
    <div class="col-3">
      <div class="form-group mt-1 mb-1">
        <%= form.label :name %>
        <%= form.text_field :name, class: "form-control" %>
      </div>
      <div class="form-group mt-1 mb-1">
        <%= form.label :about %>
        <%= form.text_area :about, class: "form-control" %>
      </div>
    </div>
  </div>
  <%= form.submit @artist.new_record? ? "Create Artist" : "Update Artist", class: "btn btn-primary" %>
<% end %>

app/views/artists/index.html.erb
<div class="container mt-2 mb-2">
  <h3>Artists</h3>
  <%= link_to "New Artist", new_artist_path %>
  <table class="table caption-top">
    <caption>List of artists</caption>
    <thead>
      <tr>
        <th>#</th>
        <th>Name</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @artists.each do |artist| %>
        <tr>
          <th><%= artist.id %></th>
          <td><%= link_to artist.name, artist_path(artist) %></td>
          <td><%= link_to "Posts", artist_posts_path(artist), class: "btn btn-sm btn-primary" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/artists/show.html.erb
<div class="container mt-2 mb-2">
  <h3>
    <%= @artist.name %>
    <%= link_to edit_artist_path(@artist) do %>
      <% fa_icon "pencil" %>
    <% end %>
  </h3>
  <div class="row">
    <div class="col-3">
      <table class="table">
        <tbody>
          <tr>
            <th>About</th>
            <td><%= @artist.about %></td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>