config/routes.rb
Rails.application.routes.draw do
  root to: 'sessions#new'
  post 'login_user', to: 'sessions#login_user'
  delete 'logout_user', to: 'sessions#logout_user'
  post 'login_artist', to: 'sessions#login_artist'
  delete 'logout_artist', to: 'sessions#logout_artist'
  resource :embed, only: %i[update]
  resources :artworks, only: %i[index] do
    member do
      put :move
    end
  end
  draw :admin
  draw :artist_module
  draw :api
  draw :sidekiq
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  email           :string
#  name            :string
#  password_digest :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
class User < ApplicationRecord
  has_secure_password
  validates :name, :email, presence: true

  scope :all_except, ->(user_id) { where.not(id: user_id) }
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < ApplicationController
    before_action :set_user, except: %i[index new create]

    def index
      @users = User.all_except(current_user.id).order(id: :asc)
    end

    def new
      @user = User.new
    end

    def create
      @user = User.new(create_params.merge(password: temporary_password))
      if @user.save
        users_mailer.send_welcome_email(temporary_password: temporary_password)
                    .deliver_later
        redirect_to admin_user_path(@user), success: "#{@user.name} successfully created."
      else
        flash[:danger] = user_errors
        render :new
      end
    end

    def edit
      redirect_to users_path, warning: "User not found." unless @user.present?
    end

    def update
      @user.assign_attributes(update_params)
      if @user.save
        redirect_to admin_user_path(@user), success: "#{@user.name} successfully updated."
      else
        flash[:danger] = user_errors
        render :edit
      end
    end

    def edit_password
      redirect_to users_path, warning: "User not found." unless @user.present?
    end

    def update_password
      @user.assign_attributes(update_password_params)
      if @user.save
        redirect_to admin_user_path(@user), success: "Password successfully updated."
      else
        flash[:danger] = user_errors
        render :edit
      end
    end

    def show
      redirect_to admin_users_path, warning: "User not found." unless @user.present?
    end
    
    def reset_password
      @user.update(password: temporary_password)
      users_mailer.send_reset_password_email(temporary_password: temporary_password)
                  .deliver_later
    end

    private

    def create_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    def update_params
      params.require(:user).permit(:name, :email)
    end

    def update_password_params
      params.require(:user).permit(:password, :password_confirmation)
    end

    def temporary_password
      @temporary_password ||= SecureRandom.hex(10)
    end

    def users_mailer
      UsersMailer.with(user_id: @user.id)
    end

    def set_user
      @user = User.find_by(id: params[:id])
    end

    def user_errors
      @user.errors.full_messages.join(', ')
    end
  end
end

app/views/users/_form.html.erb
<%= form_with model: @user, method: @user.new_record? ? :post : :put do |form| %>
  <div class="row">
    <div class="col-4">
      <div class="form-group mt-1 mb-1">
        <%= form.label :name %>
        <%= form.text_field :name, class: "form-control" %>
      </div>
      <div class="form-group mt-1 mb-1">
        <%= form.label :email %>
        <%= form.email_field :email, class: "form-control" %>
      </div>
      <% if @user.new_record? %>
        <%= render partial: 'password_fields', locals: { form: form } %>
      <% end %>
    </div>
  </div>
  <%= form.submit @user.new_record? ? "Create User" : "Update User", class: "btn btn-primary" %>
<% end %>

app/views/users/edit.html.erb
<div class="container mt-2 mb-2">
  <h3>Edit <%= @user.name %></h3>
  <%= render partial: 'form' %>
</div>

app/views/users/edit_password.html.erb
<div class="container mt-2 mb-2">
  <h3>Change <%= @user.name %>'s Password</h3>
  <%= form_with model: @user, method: :put do |form| %>
    <div class="row">
      <div class="col-4">
        <%= render partial: 'password_fields', locals: { form: form } %>
      </div>
    </div>
    <%= form.submit "Update Password", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/users/index.html.erb
<div class="container mt-2 mb-2">
  <h3>Users</h3>
  <%= link_to "New User", new_user_path %>
  <table class="table caption-top">
    <caption>List of users</caption>
    <thead class="thead-light">
      <tr>
        <th>#</th>
        <th>Name</th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <th><%= user.id %></th>
          <td><%= link_to "#{user.name}", user_path(user) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/new.html.erb
<div class="container mt-2 mb-2">
  <h3>New User</h3>
  <%= render partial: 'form' %>
</div>

app/views/users/show.html.erb
<div class="container mt-2 mb-2">
  <div class="row">
    <h3>
      <%= @user.name %>
      <%= link_to edit_user_path(@user) do %>
        <% fa_icon "pencil" %>
      <% end %>
    </h3>
  </div>
  <div class="row">
    <div class="col-3">
      <table class="table">
        <tbody>
          <tr>
            <th>E-mail</th>
            <td><%= @user.email %></td>
          </tr>
          <tr>
            <th>Password</th>
            <td><%= link_to "Change Password", edit_password_user_path %></td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>